### ISSUE TITLE
Bug: todo text duplicates

### ISSUE THREAD

**Issue by esquinas** [marcusasplund/hyperapp-todo-simple#27]
Hi, I got unexpected behaviour when I do this:
1. Open the todo app demo
2. Write `Don't` into the *Add new todo* input box. 
3. Press intro.
4. Tap/click on right-hand side of the `Don't` task to edit it.
5. Press intro. This moves the cursor to a new line below, in the same task, instead of creating a new one.
6. Write `repeat this`.
7. Click away. 
8. Now the task shows this text :
```text
Don'trepeat this
repeat this
```
Weird!

BTW, the `state` output below shows this:
```json
{
  "input": "",
  "placeholder": "Add new todo",
  "todos": [
    {
      "done": false,
      "id": "4a7bdbd4-8bb5-4258-8650-7a62654ce169",
      "value": "Don'trepeat this"
    }
  ]
}
```
I've inspected the generated html and it seems that the app creates a `<br>` that doesn't register in the raw `todos[0].value`. Not even as a `\n`.

Sorry if this issue is not formatted correctly. Actually this is the first issue I submit on Github.
I hope this helps improve the awesome Hyperapp framework. 
Regards!
  

![screenshot-2017-12-5 hyperapp todo](https://user-images.githubusercontent.com/9311114/33627665-85c4637c-d9fe-11e7-85ba-9439b731defb.png)

**Comment by marcusasplund** [comment]
Thx for the heads up. I can reproduce that issue. Interesting bug! I am not sure that the demo [https://pap.as/hyperapp/todo/](https://pap.as/hyperapp/todo/) is the latest version, i will check that first.

**Comment by marcusasplund** [comment]
Ok, i think i've fixed it now. Still have not got my head around completely with the Hyperapp 0.16.2 API, but i believe this should be somewhat correct. 
Please test again and report if you still can reproduce the issue. Oh, and try to open the url in incognito mode and/or clear previous service worker. In Chrome: open dev tools (F11) > select tab "Application" > click on "Clear storage" in the left pane > go to right pane "Clear storage", scroll down and click the button "Clear site data" 
Otherwise you might still be stucked with an older version.

**Comment by esquinas** [comment]
Hi Marcus, that was quick! 

I could reproduce the bug again by copy/pasting from a text editor. Altough it wasn't really straightfoward. 
Maybe a cosmetic solution, but good enough for a demo. :ok_hand:
  
The real problem here would be if it has something to do with the way Hyperapp parses text inputs into the storage and back to html. However I cannot test for this right now. I'd be good to check.

Thanks :+1:
